eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8070
spring:
  application:
    name: schools
  datasource:
    url: jdbc:mysql://localhost:3306/schools_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

application:
  config:
    students-url: http://localhost:8222/api/v1/students

management:
  tracing:
    sampling:
      probability: 1.0
